# Generated by Django 4.2.13 on 2024-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("led_status", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
